import type { Translations } from "./pl";

export const en: Translations = {
  // --- Common ---
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  edit: "Edit",
  close: "Close",
  back: "Go back",
  retry: "Try again",
  active: "Active",
  inactive: "Inactive",
  confirm: "Confirm",

  // --- Dashboard ---
  dashboard: "Dashboard",
  dashboardSubtitle: "Organise your month and craft AI-guided lessons.",
  assistantTip: "Assistant Tip",
  assistantTipBody:
    'Most children are curious about "Autumn Leaves" this week — try it as a day topic!',
  pendingTasks: "Pending Tasks",
  noTasks: "No pending tasks – all clear!",
  urgent: "Urgent",

  // --- Profiles ---
  careManagement: "Care Management",
  specialRequirements: "Special Requirements",
  gdprBanner:
    "This view is filtered for specialised care. Data is encrypted and compliant with local educational privacy regulations (RODO).",
  addChildProfile: "Add Child Profile",
  editChildProfile: "Edit Child Profile",
  childName: "Child's Name",
  conditionDescription: "Condition Description",
  conditionDescriptionHint:
    "Describe the child's needs in your own words. This text is anonymised before being sent to AI.",
  conditionDescriptionPlaceholder:
    "e.g. Moves by wheelchair, needs ramp access and extended time for transitions",
  childNamePlaceholder: "e.g. Leo",
  conditionDescriptionRequired: "Please describe the child's special needs.",
  nameRequired: "Name is required.",
  saveProfile: "Save Profile",
  saveChanges: "Save Changes",
  deleteProfile: "Delete Profile",
  deleteProfileConfirm: "Remove %name%? This cannot be undone.",

  // --- Day Plan ---
  planHeader: "Day Plan",
  createLesson: "Create Lesson",
  noPlan: "No plan for this day",
  dayTopic: "Day Topic",
  topicPlaceholder: "Enter topic (optional)",
  generatePlan: "Generate Lesson Plan",
  aiConsiders: "What AI will consider",
  season: "Season",
  upcoming: "Upcoming",
  noSpecialProfiles: "No special profiles",
  tipTitle: "Tip",
  tipBody:
    "Providing specific classroom materials helps AI create more relevant activities.",
  generating: "Generating plan...",
  planError: "Generation error",
  share: "Share",
  regenerate: "Regenerate",
  regenerateTitle: "Generate a new plan?",
  regenerateBody: "The current plan will be replaced. This cannot be undone.",
  deletePlan: "Delete plan",
  deletePlanConfirm: "Delete the plan for this day? This cannot be undone.",
  pedagogicalGoals: "Pedagogical Goals",
  curriculumPoints: "Core Curriculum",
  adaptations: "Adaptations",

  // --- Settings ---
  settings: "Settings",
  appInfo: "App Information",
  language: "Language",
  languageLabel: "Choose app language",
  aiStatus: "AI Gemini",
  aiActive: "Active",
  aiStatusBody:
    "Lesson plans are generated by Google Gemini 2.0 Flash. The model responds within seconds.",
  // --- Seasons ---
  seasonSpring: "Spring",
  seasonSummer: "Summer",
  seasonAutumn: "Autumn",
  seasonWinter: "Winter",

  // --- Day plan extras ---
  activeProfiles: (n: number) =>
    `${n} active special profile${n === 1 ? "" : "s"}`,
  downloadingModel: "Downloading AI model to device",
  generatingPlan: "AI is creating a lesson plan…",
  shareLabel: "Share",
  apiKeyMissing:
    "API key is not configured. Please contact your administrator.",

  privacyNote:
    "Children's names are never sent to the cloud. Before every AI call, data is anonymised on device.",

  // --- AI prompt language instruction ---
  aiLanguageInstruction: "Respond entirely in English.",
};
